version: '3'

services:
  db:
    image: 'postgres:12-alpine'
    container_name: 'macinfo_db'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    env_file:
      - '.env'

  redis:
    image: 'redis:5-alpine'
    container_name: 'macinfo_redis'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
    env_file:
      - '.env'

  web:
    container_name: 'macinfo_api'
    depends_on:
      - 'db'
      - 'redis'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/project'
    env_file:
      - '.env'
    environment:
      - RUBYOPT=-W:no-deprecated -W:no-experimental

volumes:
  redis:
  postgres:
